import Head from 'next/head';
import Header from "../components/Globales/Header"
import { TitleH1 } from "../components/Globales/StyleBase"
import MediosDePago from "../components/Globales/PaymentMethods"
import Poster from '../components/Inscripciones/Poster';
import Footer from '../components/Globales/Footer';


const { Inscription } = require("../components/Inscripciones/Inscripciones")


const Inscripciones = ()=>{

    return(
        <>
        <Head>
            <title>Revolution Dance</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <main>
            <Inscription />
            <MediosDePago />
            <Poster />
        </main>

        <Footer />
        </>
    )
}

export default Inscripciones