import Head from 'next/head';
import Header from "../components/Globales/Header"
import { TitleH1 } from "../components/Globales/StyleBase"
import MediosDePago from "../components/Globales/PaymentMethods"
import Poster from '../components/Inscripciones/Poster';
import Footer from '../components/Globales/Footer';


const { Inscription } = require("../components/Inscripciones/Inscripciones")


const Inscripciones = ()=>{

    return(
        <>
        <Head>
        <title>Revolution Dance</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Caveat:wght@700&family=Poppins:wght@400;500;700&display=swap"/>
        </Head>
        <Header />
        <main>
        <Inscription />
        <MediosDePago />
        <Poster />
        </main>
        <Footer />
        </>
    )
}

export default Inscripciones